### ISSUE TITLE
Add license at top level of repo

### ISSUE THREAD

**Issue by bielsnohr** [albertdahlin/elm-advent-of-code#1]
As an Elm newbie, I think your repo looks like a great way to structure my own attempts for Advent of Code. Would you be happy to put an open source license in your repo so that I can fork and modify it for my own purposes? I imagine you are quite familiar with the license options available, but this is a great website if you are not sure which to choose: https://choosealicense.com/

Thanks in advance!

**Comment by albertdahlin** [comment]
Sure, added a MIT license.

**Comment by bielsnohr** [comment]
Awesome, thank you!
